#!/usr/bin/env python3
"""Seed wave-1 records (from 2026-10-08 deep research report) as src/records/*.json."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "src")
REC = os.path.join(SRC, "records")
os.makedirs(REC, exist_ok=True)

TOPICS = [
    {"id": "epstein", "title": "The Epstein Files",
     "lede": "Court records, flight logs, FBI files and DOJ releases — what the paper trail actually proves, and which viral claims have no paper trail at all.",
     "code": "DSF-01"},
    {"id": "sept11", "title": "9/11: The Documents",
     "lede": "The Commission Report, the NIST engineering studies, the declassified 28 pages and the FBI Vault — the primary record of September 11, 2001.",
     "code": "DSF-02"},
    {"id": "jfk", "title": "The JFK Files",
     "lede": "Six million pages and counting: the NARA assassination-records releases, including the 80,000-page 2025 tranche.",
     "code": "DSF-03"},
    {"id": "intel-abuses", "title": "The Deep State, On the Record",
     "lede": "The parts of 'deep state' lore that turned out to be real — proven by official investigations, not internet threads.",
     "code": "DSF-04"},
    {"id": "bankers", "title": "Rothschild & Morgan",
     "lede": "Two banking dynasties: the documented history versus the conspiracy claims — checked against archives and fact-checkers.",
     "code": "DSF-05"},
    {"id": "grove", "title": "Bohemian Grove & Bilderberg",
     "lede": "Secretive elite gatherings are real. Secret world government is not. The documented facts, separated from the folklore.",
     "code": "DSF-06"},
    {"id": "satanic-panic", "title": "Satanic Panic & Adrenochrome",
     "lede": "From the McMartin trial to QAnon: the origin chain of ritual-abuse claims, and what investigators actually found.",
     "code": "DSF-07"},
    {"id": "clinton", "title": "The Clinton Files",
     "lede": "The FBI email investigation, the Benghazi report and the Clinton Foundation — findings versus talking points.",
     "code": "DSF-08"},
    {"id": "bush-era", "title": "Bush-Era Files",
     "lede": "Torture memos, WMD intelligence and the CIA interrogation report — the declassified paper trail of the 2000s.",
     "code": "DSF-09"},
]

RECORDS = [
# ---------------- 9/11 ----------------
dict(id="911-commission-report", topic="sept11", title="The 9/11 Commission Report",
     date="2004-07-22", kind="document", status="verified",
     summary="Final report of the bipartisan National Commission on Terrorist Attacks Upon the United States. Establishes that 19 al-Qaeda hijackers carried out the attacks and catalogues institutional failures (FBI–CIA info sharing, watchlisting, FAA/NORAD response, the August 6 2001 PDB). On insider trading it is explicit: exhaustive SEC/FBI investigations 'uncovered no evidence that anyone with advance knowledge of the attacks profited through securities transactions.' Commission chairs Kean and Hamilton later charged the CIA obstructed the Commission.",
     sources=[{"label": "Official full text (GPO archive)", "url": "https://govinfo.library.unt.edu/911/report/index.htm"}],
     tags=["9/11", "commission", "insider trading"]),
dict(id="nist-wtc-reports", topic="sept11", title="NIST World Trade Center Reports (NCSTAR 1 & 1A)",
     date="2005-09-01", kind="document", status="verified",
     summary="Federal Building and Fire Safety Investigation of the World Trade Center Disaster. Concludes each tower collapsed from aircraft impact damage, dislodged fireproofing and multi-floor fires — floor trusses sagged, pulled exterior columns inward, progressive collapse. WTC 7 (NCSTAR 1A, Nov 2008): thermal expansion failed Column 79 — 'the first known instance of the total collapse of a tall building primarily due to fires.' NIST's FAQ directly rebuts controlled demolition/thermite: no blast evidence; a thermite operation would have needed many thousands of pounds placed inconspicuously.",
     sources=[{"label": "NIST final report", "url": "https://www.nist.gov/publications/federal-building-and-fire-safety-investigation-world-trade-center-disaster-final-report?pub_id=909017"}],
     tags=["9/11", "WTC", "engineering"]),
dict(id="28-pages", topic="sept11", title="The Declassified '28 Pages' on Saudi Links",
     date="2016-07-15", kind="document", status="verified",
     summary="Part IV of the 2002 Joint Inquiry into pre-9/11 intelligence, redacted at the Bush administration's insistence and released after a 13-year bipartisan push. Summarizes investigative LEADS about Saudi officials' and suspected agents' financial/logistical support to hijackers — and reaches no conclusions. The White House, Kean/Hamilton and the 2015 9/11 Review Commission all said the pages contain no evidence of institutional Saudi government funding of al-Qaeda.",
     sources=[{"label": "28pages.org (House Intel PDF + transcript)", "url": "http://28pages.org/page/6/"}],
     tags=["9/11", "Saudi Arabia", "declassified"]),
dict(id="fbi-vault-911", topic="sept11", title="FBI Vault: 9/11 Collections",
     date="2001-01-01", kind="document", status="verified",
     summary="The FBI's FOIA library hosts the 9/11 Commission Report investigative files (monthly releases 2001–2004), material released under Executive Order 14040 (2021 declassification review), and Pentagon exterior/interior/debris photos plus emergency-response footage.",
     sources=[{"label": "FBI Vault — 9/11 search", "url": "https://vault.fbi.gov/search?SearchableText=9-11&utm_source"}],
     tags=["9/11", "FBI", "FOIA"]),
# ---------------- JFK ----------------
dict(id="jfk-2023-release", topic="jfk", title="NARA JFK Releases (2023)",
     date="2023-01-01", kind="document", status="verified",
     summary="NARA posted thousands of formerly-redacted records: CIA Office of Legislative Counsel journals, JMWAVE cables, CIA Oswald files, Rockefeller Commission/HSCA-era material and DOD files.",
     sources=[{"label": "NARA 2023 release index", "url": "https://www.archives.gov/research/jfk/release-2023"}],
     tags=["JFK", "NARA", "CIA"]),
dict(id="jfk-2025-release", topic="jfk", title="EO 14176: 80,000+ Pages Released (2025)",
     date="2025-03-18", kind="document", status="verified",
     summary="Executive Order 14176 (Jan 23, 2025) ordered full release of JFK/RFK/MLK assassination records. On March 18, 2025 NARA released 80,000+ pages in under 24 hours — 'one of the largest single releases of records in U.S. history.' The full collection exceeds 6 million pages. As of late 2026, no official review has identified a 'smoking gun' overturning the Warren Commission's lone-gunman conclusion.",
     sources=[{"label": "NARA release announcement", "url": "https://www.archives.gov/news/articles/jfk-records-release"},
              {"label": "NARA JFK FAQ", "url": "https://www.archives.gov/research/jfk/faqs"}],
     tags=["JFK", "NARA", "declassified"]),
# ---------------- intel abuses ----------------
dict(id="eisenhower-farewell", topic="intel-abuses", title="Eisenhower's Farewell Address (1961)",
     date="1961-01-17", kind="document", status="verified",
     summary="'In the councils of government, we must guard against the acquisition of unwarranted influence, whether sought or unsought, by the military-industrial complex. The potential for the disastrous rise of misplaced power exists and will persist.' He also warned policy could become 'captive of a scientific-technological elite.' He never said 'deep state' — a 21st-century term (from Turkish 'derin devlet').",
     sources=[{"label": "NARA milestone documents", "url": "https://www.archives.gov/milestone-documents/president-dwight-d-eisenhowers-farewell-address"}],
     tags=["deep state", "military-industrial complex"]),
dict(id="church-committee", topic="intel-abuses", title="Church Committee Final Report (1976)",
     date="1976-04-29", kind="document", status="verified",
     summary="Senate Select Committee on Intelligence Activities: 126 meetings, ~800 witnesses, 110,000 documents. Found 'intelligence excesses, at home and abroad' spanning FDR to the early 1970s — CIA assassination plots (e.g. Castro), COINTELPRO, NSA SHAMROCK/MINARET monitoring Americans. Led to permanent intelligence committees and FISA (1978).",
     sources=[{"label": "Senate: Church Committee", "url": "https://www.senate.gov/about/powers-procedures/investigations/church-committee.htm"}],
     tags=["deep state", "CIA", "FBI", "NSA"]),
dict(id="cointelpro", topic="intel-abuses", title="COINTELPRO: The FBI's Own Files",
     date="1956-08-28", kind="document", status="verified",
     summary="FBI Counter Intelligence Program, authorized by Hoover in 1956. Declassified files show warrantless wiretapping, surreptitious entry, mail opening, paid informants, fabricated correspondence and forged documents against civil-rights, antiwar and other groups — including the 1964 anonymous letter urging MLK to kill himself. Exposed by the 1971 Media, PA office burglary; terminated April 1971. The FBI's own Vault summary concedes it was 'rightfully criticized... for abridging first amendment rights.'",
     sources=[{"label": "FBI Vault: COINTELPRO", "url": "https://vault.fbi.gov/cointel-pro"}],
     tags=["deep state", "FBI", "MLK"]),
dict(id="iran-contra", topic="intel-abuses", title="Iran-Contra: Tower Commission & Walsh Report",
     date="1987-02-26", kind="document", status="verified",
     summary="The Reagan administration secretly sold arms to Iran and diverted proceeds to Nicaragua's Contras despite the Boland Amendment ban. Tower Commission (Feb 1987): Reagan's 'lax managerial style.' Walsh final report (Aug 1993): 14 officials charged, 11 convictions/guilty pleas; arms sales 'contravened U.S. Government policy'; systematic document destruction documented. George H.W. Bush's Dec 24, 1992 pardons ended the probe.",
     sources=[{"label": "Iran-Contra affair (report citations)", "url": "https://en.wikipedia.org/wiki/Iran-Contra_affair"}],
     tags=["deep state", "Reagan", "CIA"]),
# ---------------- bankers ----------------
dict(id="rothschild-history", topic="bankers", title="Rothschild Family: The Documented History",
     date="1810-01-01", kind="document", status="verified",
     summary="From Frankfurt's Judengasse: Mayer Amschel Rothschild (1744–1812) founded 'M A Rothschild und Söhne' in 1810; five sons built a Europe-wide network underwriting sovereign debt and financing governments including Britain's Napoleonic war effort. Today Rothschild & Co is an advisory/wealth-management firm. It owns no central banks.",
     sources=[{"label": "Rothschild Archive: Mayer Amschel", "url": "https://family.rothschildarchive.org/people/21-mayer-amschel-rothschild-1744-1812"},
              {"label": "Rothschild Archive timeline", "url": "https://www.rothschildarchive.org/exhibitions/timeline"}],
     tags=["Rothschild", "banking"]),
dict(id="jp-morgan-history", topic="bankers", title="J.P. Morgan: The Documented History",
     date="1913-03-31", kind="document", status="verified",
     summary="John Pierpont Morgan (1837–1913) financed the railroads, steel and utilities that industrialized the US; formed U.S. Steel (1901). Died March 31, 1913 — months BEFORE the Federal Reserve Act (Dec 23, 1913). He did not create the Fed.",
     sources=[{"label": "JPMorganChase: Our history", "url": "http://jpmorganchase.com/about/our-history"}],
     tags=["Morgan", "banking", "Federal Reserve"]),
# ---------------- grove ----------------
dict(id="bohemian-grove", topic="grove", title="Bohemian Grove: What Is Documented",
     date="1971-05-13", kind="document", status="verified",
     summary="The Bohemian Club (est. 1872) holds an annual all-male summer encampment at Monte Rio, CA; the opening 'Cremation of Care' is a theatrical pageant (filmed by infiltrators in 2000). On White House tapes (May 13, 1971) Nixon called it 'the most faggy goddamned thing you could ever imagine... I attend from time to time.' No primary-source evidence supports claims of satanic rituals or human sacrifice; no criminal case has ever been tied to the Grove.",
     sources=[{"label": "Nixon Library tape subject logs", "url": "https://www.nixonlibrary.gov/sites/default/files/forresearchers/find/tapes/finding_aids/tapesubjectlogs/oval552.pdf"}],
     tags=["Bohemian Grove", "Nixon"]),
dict(id="bilderberg", topic="grove", title="Bilderberg Meetings: What Is Documented",
     date="1954-05-01", kind="document", status="verified",
     summary="Annual invitation-only conference (~120–150 politicians, CEOs, central bankers, academics) under the Chatham House Rule since 1954. The organization itself publishes each year's agenda and participant list (2024 Madrid: 131 participants; 2025 Stockholm: 121). No primary source — minutes, directives, testimony — shows decision-making authority or a secret world government.",
     sources=[{"label": "bilderbergmeetings.org", "url": "https://www.bilderbergmeetings.org"}],
     tags=["Bilderberg", "elites"]),
# ---------------- epstein ----------------
dict(id="epstein-npa", topic="epstein", title="The 2008 Non-Prosecution Agreement",
     date="2007-09-24", kind="document", status="verified",
     summary="Facing a 53-page federal indictment, Epstein's team negotiated an NPA with U.S. Attorney Acosta's office. He pleaded to two Florida state charges, served ~13 months of an 18-month county-jail sentence with work release, and the NPA immunized him, four named accomplices and unnamed 'any potential co-conspirators' from federal prosecution in S.D. Florida. Victims were not informed (later found to violate the Crime Victims' Rights Act). DOJ's OPR called it 'extraordinary' and found 'poor judgment,' no impermissible considerations.",
     sources=[{"label": "Plea deal details (fact check)", "url": "https://factually.co/fact-checks/justice/jeffrey-epstein-2007-plea-deal-details-9adc54"}],
     tags=["Epstein", "court records"]),
dict(id="epstein-indictment", topic="epstein", title="2019 SDNY Indictment (19 Cr. 490)",
     date="2019-07-08", kind="document", status="verified",
     summary="United States v. Jeffrey Epstein: conspiracy to commit sex trafficking of minors (§371) and sex trafficking of minors (§1591), alleging conduct 2002–2005 in New York and Palm Beach — girls as young as 14 enticed to 'massages' escalating to sex acts for cash, victims recruited to recruit others. Epstein was found dead August 10, 2019 (suicide, per the NYC medical examiner); the criminal case abated. Guilt was never adjudicated.",
     sources=[{"label": "DOJ: U.S. v. Jeffrey Epstein", "url": "https://www.justice.gov/usao-sdny/programs/victim-witness-services/united-states-v-jeffrey-epstein-19-cr-490-rmb"}],
     tags=["Epstein", "court records"]),
dict(id="epstein-flight-logs", topic="epstein", title="The Flight Logs (Court Exhibits)",
     date="2015-12-10", kind="document", status="verified",
     summary="Pilot manifests for Epstein's aircraft entered as exhibits in Giuffre v. Maxwell, introduced at Maxwell's trial, and released via FOIA/DOJ disclosures (2,618+ known flights compiled). Names include Bill Clinton, Donald Trump, Prince Andrew, Kevin Spacey, Naomi Campbell, Chris Tucker, Alan Dershowitz, Jean-Luc Brunel, Larry Summers. They show who was on which flights — appearance establishes association, NOT wrongdoing, a distinction emphasized by DOJ, courts and fact-checkers.",
     sources=[{"label": "Flight logs explainer", "url": "https://factually.co/fact-checks/justice/epstein-flight-logs-photographs-private-jet-records-linked-to-giuffre-8dcc6f"}],
     tags=["Epstein", "flight logs"]),
dict(id="epstein-vault-doj", topic="epstein", title="FBI Vault & DOJ Epstein Disclosures",
     date="2024-01-01", kind="document", status="verified",
     summary="FBI Vault collection (22 parts of investigative records); DOJ disclosure page; ~900 pages unsealed Jan 2024 from Giuffre v. Maxwell (depositions, emails, contact book). Feb 2025 'Phase 1' release was mostly already-public material. Under the Epstein Files Transparency Act, ~3.5M pages, ~2,000 videos and ~180,000 photos were released Dec 2025–Jan 2026. DOJ warned some circulating material may be fake or planted.",
     sources=[{"label": "FBI Vault: Jeffrey Epstein", "url": "https://vault.fbi.gov/jeffrey-epstein"},
              {"label": "DOJ disclosures", "url": "https://www.justice.gov/epstein/doj-disclosures"}],
     tags=["Epstein", "FBI", "DOJ"]),
dict(id="epstein-memo-2025", topic="epstein", title="July 2025 DOJ/FBI Memo: No 'Client List'",
     date="2025-07-07", kind="document", status="verified",
     summary="Unsigned two-page DOJ/FBI memo after systematic review: (1) no incriminating 'client list' found; (2) no credible evidence Epstein blackmailed prominent individuals; (3) suicide finding reaffirmed (medical examiner + 2023 DOJ OIG report); (4) no further disclosures warranted at that time. AG Bondi had said in Feb 2025 a 'client list' was 'sitting on my desk'; she walked that back July 8. No document functioning as a client list has ever been entered as an exhibit in any Epstein/Maxwell case.",
     sources=[{"label": "Memo summary", "url": "https://epsteinwiki.com/knowledge-base/the-july-2025-doj-and-fbi-epstein-memo-what-it-said-and-what-the-records-show/"}],
     tags=["Epstein", "client list", "DOJ"]),
dict(id="maxwell-trial", topic="epstein", title="Ghislaine Maxwell Trial & Conviction",
     date="2021-12-29", kind="document", status="verified",
     summary="S.D.N.Y. trial Nov 29–Dec 29, 2021: four accuser witnesses testified under oath to grooming and sexual abuse as minors with Maxwell's assistance; exhibits included flight logs, the address book, photographs and financial records. Guilty on 5 of 6 counts; sentenced June 2022 to 20 years; affirmed by the Second Circuit (2024); Supreme Court declined review (Oct 2025). Note: trafficking of victims TO third parties was not proven at trial and remains alleged, not established.",
     sources=[{"label": "Trial knowledge base", "url": "https://epsteinwiki.com/knowledge-base/maxwell-criminal-trial-united-states-v-ghislaine-maxwell/"}],
     tags=["Epstein", "Maxwell", "court records"]),
# ---------------- satanic panic ----------------
dict(id="mcmartin-trial", topic="satanic-panic", title="The McMartin Preschool Trial (1983–1990)",
     date="1990-01-18", kind="document", status="verified",
     summary="Seven years, ~$15–16M — the longest, most expensive criminal trial in US history at the time. Allegations included satanic rituals, tunnels under the school and animal sacrifice. Result: NO convictions. Peggy McMartin Buckey acquitted of all counts Jan 18, 1990; Ray Buckey acquitted on 52 of 65 counts, rest hung/dismissed. Suggestive child-interview techniques were discredited and reshaped abuse investigations nationwide.",
     sources=[{"label": "McMartin preschool trial", "url": "http://en.wikipedia.org/wiki/McMartin_preschool_trial"}],
     tags=["satanic panic", "McMartin"]),
dict(id="lanning-report", topic="satanic-panic", title="FBI 1992: Lanning's 'Investigator's Guide to Ritual Child Abuse'",
     date="1992-01-01", kind="document", status="verified",
     summary="Supervisory Special Agent Kenneth V. Lanning (Behavioral Science Unit): no evidence of large-scale organized satanic cults abusing children in the US; crimes with bizarre/ritualistic elements do occur and must be distinguished from organized-cult claims; warned against suggestive interviewing. Frequently misquoted as a 'seven-year FBI study' — it is an investigator's guide, and Lanning did not declare all such claims a hoax.",
     sources=[{"label": "Lanning report full text (Wikisource)", "url": "https://en.wikisource.org/wiki/Page:Lanning_Report_1992_Investigator%27s_guide_to_allegations_of_%27ritual%27_child_abuse.pdf/20"}],
     tags=["satanic panic", "FBI"]),
dict(id="adrenochrome-origins", topic="satanic-panic", title="Adrenochrome: From Fiction to QAnon",
     date="1971-01-01", kind="document", status="verified",
     summary="Origin chain of the elite baby-eating/adrenochrome claim: Hunter S. Thompson's 1971 FICTION 'Fear and Loathing in Las Vegas' → Gilliam's 1998 film → 4chan /x/ (2013) and /pol/ (2014) → Pizzagate (2016) → QAnon (2017+). Scientific reality: adrenochrome is a real chemical (oxidized adrenaline) — unstable, no fountain-of-youth properties, synthesized industrially. NO primary source — no court filing, FBI file, testimony or DOJ release — connects Epstein or any public figure to adrenochrome harvesting or ritual sacrifice.",
     sources=[{"label": "McGill OSS: QAnon's adrenochrome quackery", "url": "https://www.mcgill.ca/oss/article/pseudoscience/qanons-adrenochrome-quackery"}],
     tags=["adrenochrome", "QAnon"]),
# ---------------- clinton ----------------
dict(id="clinton-emails", topic="clinton", title="FBI Clinton Email Investigation ('Midyear Exam')",
     date="2016-07-05", kind="document", status="verified",
     summary="Comey's statement: Clinton was 'extremely careless' with classified info on personal servers (~110 emails in 52 chains classified at the time of sending); 'no clear evidence' of intent; 'no reasonable prosecutor' would bring charges — declined. Briefly reopened Oct 28, 2016 (Weiner laptop), closed Nov 6 with conclusions unchanged. DOJ IG (June 2018) criticized Comey's public statements but found no evidence political bias affected the declination.",
     sources=[{"label": "FBI: Comey statement", "url": "https://www.fbi.gov/news/press-releases/statement-by-fbi-director-james-b-comey-on-the-investigation-of-secretary-hillary-clinton2019s-use-of-a-personal-e-mail-system"}],
     tags=["Clinton", "FBI", "emails"]),
dict(id="benghazi-report", topic="clinton", title="House Benghazi Committee Report (2016)",
     date="2016-06-28", kind="document", status="verified",
     summary="~800 pages on the Sept 11, 2012 attack that killed Ambassador Stevens and three others: State failed to protect diplomats; CIA misread Libya's danger; DOD assets never reached Benghazi in time. Also found: NO new evidence of culpability by Clinton; NO 'stand down' order was issued; US forces in Europe could not have arrived in time.",
     sources=[{"label": "Benghazi committee report summary", "url": "https://en.wikipedia.org/wiki/United_States_House_Select_Committee_on_Benghazi"}],
     tags=["Clinton", "Benghazi"]),
dict(id="clinton-foundation", topic="clinton", title="Clinton Foundation: Facts vs Claims",
     date="1997-01-01", kind="document", status="verified",
     summary="Founded 1997; a public OPERATING foundation running its own programs (HIV/AIDS, climate, health). Ratings: Charity Navigator 4/4 stars; CharityWatch 'A' (~88% to mission). Documented controversies: foreign-government donations during her State tenure; disclosure lapses. Claims: 'Only 6% goes to charity' — DISPUTED (counts grants only, ignoring program expenses ~80–89%). 'Pay-to-play proven' — UNPROVEN; multiple inquiries, no charges.",
     sources=[{"label": "Clinton Foundation", "url": "https://en.wikipedia.org/wiki/Clinton_Foundation"}],
     tags=["Clinton", "foundation"]),
# ---------------- bush era ----------------
dict(id="torture-memos", topic="bush-era", title="The OLC 'Torture Memos' (2002)",
     date="2002-08-01", kind="document", status="verified",
     summary="OLC memos signed by Jay Bybee (drafted principally by John Yoo): narrowed 'torture' to pain equivalent to organ failure or death, and approved CIA 'enhanced' techniques for Abu Zubaydah. Withdrawn in 2004 by OLC head Jack Goldsmith as deeply flawed; rescinded by Obama Jan 22, 2009. DOJ OPR (2010) found professional misconduct; overruled to 'poor judgment.' No prosecutions resulted.",
     sources=[{"label": "Torture Memos", "url": "https://en.wikipedia.org/wiki/Torture_Memos"}],
     tags=["Bush", "torture", "CIA"]),
dict(id="senate-wmd-report", topic="bush-era", title="Senate Report: Prewar Iraq WMD Intelligence (2004)",
     date="2004-07-09", kind="document", status="verified",
     summary="Unanimous bipartisan S. Rept. 108-301: most key judgments in the Oct 2002 NIE on Iraq were overstated or unsupported; 'group think' presumed active WMD programs; no CIA sources inside Iraq on WMD after 1998. Did NOT find analysts changed judgments from political pressure. Phase II (2008): administration public statements (Iraq–al-Qaeda partnership, WMD claims) were NOT substantiated by available intelligence.",
     sources=[{"label": "S. Rept. 108-301 (Congress.gov)", "url": "https://www.congress.gov/committee-report/108th-congress/senate-report/301/1"}],
     tags=["Bush", "Iraq", "WMD"]),
dict(id="cia-interrogation-report", topic="bush-era", title="Senate Report: CIA Detention & Interrogation (2014)",
     date="2014-12-09", kind="document", status="verified",
     summary="Five-year SSCI study of 6.3M+ pages of CIA records; 500+ page declassified executive summary. Findings: 'enhanced interrogation techniques' were not effective; the CIA gave extensively inaccurate information about the program to policymakers and the public; management was deeply flawed; the program was far more brutal than represented (waterboarding, systematic beatings, sleep deprivation; 119+ detainees in secret 'black sites').",
     sources=[{"label": "Feinstein report summary", "url": "https://www.GlobalSecurity.org/intell/library/news/2014/intell-141209-feinstein01.htm"}],
     tags=["Bush", "CIA", "torture"]),
# ---------------- claims (disputed/unproven) ----------------
dict(id="claim-demolition", topic="sept11", title="CLAIM: Controlled demolition of the Twin Towers / WTC 7",
     date="2001-09-11", kind="claim", status="disputed",
     summary="Popular claim that explosives or thermite brought down WTC 1, 2 and 7. Counter-evidence: NIST NCSTAR 1 & 1A document a fire-driven progressive collapse mechanism with no blast evidence; NIST's FAQ quantitatively rebuts the thermite scenario. No primary source supports demolition.",
     sources=[{"label": "NIST WTC investigation", "url": "https://www.nist.gov/publications/federal-building-and-fire-safety-investigation-world-trade-center-disaster-final-report?pub_id=909017"}],
     tags=["9/11", "claim"]),
dict(id="claim-insider-trading", topic="sept11", title="CLAIM: 9/11 insider trading proves foreknowledge",
     date="2001-09-11", kind="claim", status="disputed",
     summary="Unusual put-option activity before 9/11 is cited as proof of foreknowledge. Counter-evidence: the 9/11 Commission reports exhaustive SEC/FBI investigations found no evidence anyone with advance knowledge profited — the 'highly suspicious' UAL puts were 95% one US institutional investor with no al-Qaeda ties; AMR trading traced to a Sept 9 options newsletter.",
     sources=[{"label": "9/11 Commission Report", "url": "https://govinfo.library.unt.edu/911/report/index.htm"}],
     tags=["9/11", "claim"]),
dict(id="claim-rothschild-banks", topic="bankers", title="CLAIM: Rothschilds own all the world's central banks",
     date="1846-01-01", kind="claim", status="disputed",
     summary="Viral claim that the Rothschilds secretly own the Federal Reserve and most central banks. Counter-evidence: central banks are publicly/government-owned (Bank of England nationalized 1946; the Fed 'is not owned by anyone' — created by Congress). AAP FactCheck verdict: False. The trope traces to an anonymous 1846 Paris pamphlet and 'Protocols'-era literature.",
     sources=[{"label": "AAP FactCheck", "url": "https://www.aap.com.au/factcheck/rothschilds-mass-ownership-claim-a-bankrupt-myth/"}],
     tags=["Rothschild", "claim"]),
dict(id="claim-morgan-fed", topic="bankers", title="CLAIM: J.P. Morgan created the Federal Reserve",
     date="1913-12-23", kind="claim", status="disputed",
     summary="Morgan died March 31, 1913 — before the Federal Reserve Act (Dec 23, 1913). Bankers including Paul Warburg influenced the design (Jekyll Island, 1910), but the Fed is a creature of Congress.",
     sources=[{"label": "JPMorganChase history", "url": "http://jpmorganchase.com/about/our-history"}],
     tags=["Morgan", "claim", "Federal Reserve"]),
dict(id="claim-epstein-client-list", topic="epstein", title="CLAIM: A suppressed Epstein 'client list' exists",
     date="2025-07-07", kind="claim", status="unproven",
     summary="Viral '166-name'/'200-name' lists conflate flight logs, the address book and deposition mentions. The July 2025 DOJ/FBI systematic review 'revealed no incriminating client list'; Maxwell told DOJ none exists. No document functioning as a client list has ever been an exhibit in any Epstein/Maxwell case. Existence: UNPROVEN.",
     sources=[{"label": "July 2025 memo summary", "url": "https://epsteinwiki.com/knowledge-base/the-july-2025-doj-and-fbi-epstein-memo-what-it-said-and-what-the-records-show/"}],
     tags=["Epstein", "claim"]),
dict(id="claim-satanic-cult", topic="satanic-panic", title="CLAIM: Organized satanic cults abused children en masse in the 1980s",
     date="1990-01-18", kind="claim", status="disputed",
     summary="Dozens of daycare ritual-abuse prosecutions collapsed nationwide (McMartin: zero convictions; Keller convictions overturned, declared actually innocent 2017). The FBI's 1992 Lanning report found no evidence of large-scale organized satanic cults. Nearly all the accused were eventually freed.",
     sources=[{"label": "Lanning report (Wikisource)", "url": "https://en.wikisource.org/wiki/Page:Lanning_Report_1992_Investigator%27s_guide_to_allegations_of_%27ritual%27_child_abuse.pdf/20"}],
     tags=["satanic panic", "claim"]),
dict(id="claim-benghazi-standdown", topic="clinton", title="CLAIM: A 'stand down' order was issued at Benghazi",
     date="2012-09-11", kind="claim", status="disputed",
     summary="The House Select Committee (2016) found NO stand-down order was issued, and that US forces in Europe could not have arrived in time — consistent with all prior inquiries.",
     sources=[{"label": "Benghazi committee report summary", "url": "https://en.wikipedia.org/wiki/United_States_House_Select_Committee_on_Benghazi"}],
     tags=["Clinton", "Benghazi", "claim"]),
dict(id="claim-grassy-knoll", topic="jfk", title="CLAIM: A second gunman on the grassy knoll",
     date="1963-11-22", kind="claim", status="disputed",
     summary="The HSCA's 1979 'high probability of conspiracy' rested SOLELY on acoustic analysis of the Dallas police Dictabelt recording. The FBI Laboratory review (Dec 1980) found the analyses 'did not scientifically prove' a second gunman — the finding is invalid; later audio research confirmed the open-mike motorcycle wasn't in the motorcade during the shots.",
     sources=[{"label": "FBI lab review (PDF)", "url": "http://jfk.hood.edu/Collection/FBI%20Records/062-117290/062-117290%20Volume%2025/62-117290P25b.pdf"}],
     tags=["JFK", "claim"]),
]

with open(os.path.join(SRC, "topics.json"), "w") as f:
    json.dump(TOPICS, f, indent=2, ensure_ascii=False)

for r in RECORDS:
    r["added"] = "2026-10-08"
    r["reviewed"] = True
    with open(os.path.join(REC, r["id"] + ".json"), "w") as f:
        json.dump(r, f, indent=2, ensure_ascii=False)

print(f"wrote {len(TOPICS)} topics, {len(RECORDS)} records")
